# Generated by Django 5.2.3 on 2026-02-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_created_at_lesson_is_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_preview',
        ),
    ]
